# Generated by Django 2.1.5 on 2019-01-25 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateField(auto_now_add=True)),
                ('finished', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrintFile',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False)),
                ('stl', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='printattempt',
            name='printfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='crowdprinter.PrintFile'),
        ),
        migrations.AddField(
            model_name='printattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
