# Generated by Django 2.1.5 on 2019-01-29 13:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="printattempt",
            old_name="finished",
            new_name="ended",
        ),
        migrations.AddField(
            model_name="printjob",
            name="finished",
            field=models.BooleanField(default=False),
        ),
    ]
