# Generated by Django 2.1.5 on 2019-01-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdprinter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printfile',
            name='render',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
