# Generated by Django 2.1.5 on 2019-01-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdprinter', '0002_printfile_render'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printfile',
            name='render',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
