# Generated by Django 5.1.4 on 2024-12-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0003_user_allow_messages_after_event_from_humans_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="comment",
            field=models.TextField(
                blank=True, default="", help_text="Öffentlicher Kommentar"
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="internal_comment",
            field=models.TextField(
                blank=True, default="", help_text="Interner Kommentar"
            ),
        ),
        migrations.AddField(
            model_name="printjob",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Auf der Startseite anzeigen, mit dem Link wird es immer angezeigt.",
            ),
        ),
    ]
