# Generated by Django 5.1.2 on 2024-10-30 17:53

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        (
            "crowdprinter",
            "0005_alter_printjob_file_render_alter_printjob_file_stl_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="printjob",
            name="file_render",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
