# Generated by Django 5.1.2 on 2024-10-30 17:55

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0006_alter_printjob_file_render"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
