# Generated by Django 5.1.2 on 2024-11-01 21:33

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0007_alter_printer_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="printjob",
            name="finished",
        ),
        migrations.AddField(
            model_name="printattempt",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="printjob",
            name="count_needed",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="printjobfile",
            name="job",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="crowdprinter.printjob",
            ),
        ),
    ]
