# Generated by Django 5.1.2 on 2024-11-02 16:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0009_printattempt_dropped_off"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printattempt",
            name="dropped_off",
            field=models.BooleanField(default=False),
        ),
    ]
