# Generated by Django 5.1.2 on 2024-11-23 21:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("crowdprinter", "0010_alter_printattempt_dropped_off"),
    ]

    operations = [
        migrations.AddField(
            model_name="printjob",
            name="priority",
            field=models.PositiveIntegerField(
                default=100,
                help_text="Zahl von 0 bis 100. Jobs mit kleinen Zahlen werden weiter oben angezeigt.",
            ),
        ),
    ]
